### ISSUE TITLE
gulpfile in documentation failing

### ISSUE THREAD

**Issue by sanderson-sfdc** [asciidoctor/gulp-asciidoctor#27]
I'm a newbie to gulp, so this could be my issue, but when I copy the example gulpfile, changing only the paths, and run gulp --tasks I get the following error:

```console
$ gulp --tasks
/Users/sanderson/git/mulesoft/test-pipeline/gulpfile.js:7
              .pipe(gulp.dest('targetdir'))
                                          ^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireOrImport (/Users/sanderson/.nvm/versions/node/v12.18.3/lib/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/Users/sanderson/.nvm/versions/node/v12.18.3/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/Users/sanderson/.nvm/versions/node/v12.18.3/lib/node_modules/gulp-cli/index.js:211:24)`
```

If I add a closing parenthesis to the asciidoctor pipe

```js
.pipe(asciidoctor({}))
```

`gulp --tasks` succeeds.

**Comment by ggrossetie** [comment]
Hello @sanderson-sfdc 

No, I think you are right, we need to add a closing parenthesis on the examples.
If you want to fix the documentation/code examples, I will gladly merge it 😉 

Nice catch 👍

**Comment by ggrossetie** [comment]
Fixed in https://github.com/asciidoctor/gulp-asciidoctor/pull/28
Thanks @sanderson-sfdc 👏
