### ISSUE TITLE
not working without installing asciidoctor.js in addition

### ISSUE THREAD

**Issue by blndev** [asciidoctor/gulp-asciidoctor#6]
Used Version: "gulp-asciidoctor": "^1.0.7"

Error: 

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'asciidoctor.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/daniel/src/github/restSampleServices/node-service/node_modules/gulp-asciidoctor/index.js:4:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

```

Solution:
`npm install asciidoctor.js --save`

That will (currently) install asciidoctor.js 1.5.5-1, which contains a fix with a path.

Maybe that information should be a part of the "known issues" list.

**Comment by dongwq** [comment]
v1.0.8 Released with upgrading asciidoctor.js to version 1.5.5-1 and other deps to latest.  
Any feedback are welcome.

**Comment by blndev** [comment]
👍 
Thank you.
Works fine now.
